import { NextResponse } from "next/server";
import { getAccountingData } from "@/lib/accounting/service";
import type { AccountingData } from "@/lib/accounting/types";
import { authorizeApi } from "@/lib/api-authorization";
import { getAuthenticatedTenantContext, getTenantContext } from "@/lib/tenant";

const titles: Record<string, string> = {
  "profit-and-loss": "Profit & Loss Statement",
  "balance-sheet": "Balance Sheet",
  "cash-flow-statement": "Cash Flow Statement",
  "trial-balance": "Trial Balance",
  "accounts-receivable-aging": "Accounts Receivable Aging",
  "accounts-payable-aging": "Accounts Payable Aging",
  "revenue-by-shipment": "Revenue by Shipment",
  "expense-report": "Expense Report",
};

type ReportTable = { columns: string[]; rows: (string | number)[][]; currencyColumns?: number[] };
type ReportSection = { title: string; table: ReportTable; total?: number };

export async function GET(request: Request, { params }: { params: Promise<{ type: string }> }) {
  const authorization = await authorizeApi("reports.view");
  if (!authorization.ok) return authorization.response;
  if (!(await getAuthenticatedTenantContext())) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { type } = await params;
  if (!titles[type]) return NextResponse.json({ error: "Unknown report type" }, { status: 404 });
  const url = new URL(request.url);
  const from = url.searchParams.get("from") ?? "";
  const to = url.searchParams.get("to") ?? "";
  const [data, tenant] = await Promise.all([getAccountingData(), getTenantContext()]);
  const sections = buildReport(type, data, from, to);
  const currency = tenant.company.currency;
  const generatedAt = new Date();
  const period = from || to ? `${from || "Beginning"} to ${to || "Today"}` : "All recorded transactions";
  const logo = tenant.company.logoUrl
    ? `<img src="${escapeHtml(tenant.company.logoUrl)}" alt="${escapeHtml(tenant.company.name)} logo">`
    : escapeHtml(tenant.company.name.slice(0, 2).toUpperCase());
  const html = `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(titles[type])}</title><style>
*{box-sizing:border-box}body{font-family:Arial,sans-serif;color:#172033;margin:0;background:#eef2f7}.toolbar{position:sticky;top:0;padding:12px 24px;background:#172033;color:#fff;display:flex;justify-content:flex-end}.toolbar button{background:${tenant.company.themeColor};color:#fff;border:0;border-radius:6px;padding:10px 16px;font-weight:700;cursor:pointer}.sheet{width:210mm;min-height:297mm;margin:20px auto;background:#fff;padding:18mm;box-shadow:0 12px 40px #0002}.head{display:flex;justify-content:space-between;gap:24px;border-bottom:3px solid ${tenant.company.themeColor};padding-bottom:16px}.brand{display:flex;align-items:center;gap:14px}.logo{width:58px;height:58px;border-radius:10px;background:${tenant.company.themeColor};color:#fff;display:grid;place-items:center;font-weight:800;overflow:hidden}.logo img{width:100%;height:100%;object-fit:contain}.company h1,.report h2{margin:0}.muted{color:#64748b;font-size:12px;line-height:1.6}.report{margin:28px 0 18px}.meta{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:14px}.meta div{border:1px solid #dbe3ed;border-radius:6px;padding:9px}.meta strong{display:block;font-size:11px;color:#64748b;text-transform:uppercase;margin-bottom:4px}.section{margin-top:24px}.section h3{margin:0 0 8px;font-size:15px;color:#334155}table{width:100%;border-collapse:collapse;font-size:12px}th{background:#eff4f8;color:#334155;text-transform:uppercase;font-size:10px;letter-spacing:.04em}th,td{border-bottom:1px solid #dbe3ed;padding:9px 8px;text-align:left}td.num,th.num{text-align:right;font-variant-numeric:tabular-nums}.total{display:flex;justify-content:flex-end;gap:30px;border-top:2px solid #172033;padding:10px 8px;font-weight:800}.empty{padding:24px;border:1px dashed #cbd5e1;color:#64748b;text-align:center}.footer{margin-top:36px;padding-top:12px;border-top:1px solid #dbe3ed;display:flex;justify-content:space-between;color:#64748b;font-size:10px}
@media print{body{background:#fff}.toolbar{display:none}.sheet{width:auto;min-height:auto;margin:0;padding:10mm;box-shadow:none}@page{size:A4;margin:8mm}}
</style></head><body><div class="toolbar"><button onclick="window.print()">Print / Download PDF</button></div><main class="sheet">
<header class="head"><div class="brand"><div class="logo">${logo}</div><div class="company"><h1>${escapeHtml(tenant.company.name)}</h1><div class="muted">${escapeHtml(tenant.company.address || "")}<br>${escapeHtml(tenant.company.email ?? "")}</div></div></div><div class="muted">${escapeHtml(tenant.company.taxRegistrationNumber ?? "")}</div></header>
<section class="report"><h2>${escapeHtml(titles[type])}</h2><div class="meta"><div><strong>Reporting period</strong>${escapeHtml(period)}</div><div><strong>Currency</strong>${escapeHtml(currency)}</div><div><strong>Generated by</strong>${escapeHtml(tenant.user.name)}</div><div><strong>Generated date</strong>${escapeHtml(generatedAt.toLocaleString("en-GB"))}</div></div></section>
${sections.map((section) => renderSection(section, currency)).join("")}
<footer class="footer"><span>${escapeHtml(tenant.company.name)} · ${escapeHtml(titles[type])}</span><span>Generated ${escapeHtml(generatedAt.toLocaleDateString("en-GB"))}</span></footer>
</main></body></html>`;
  return new NextResponse(html, { headers: { "content-type": "text/html; charset=utf-8", "content-disposition": `inline; filename="${type}.html"` } });
}

function buildReport(type: string, data: AccountingData, from: string, to: string): ReportSection[] {
  if (type === "profit-and-loss") {
    const revenue = data.accounts.filter((account) => account.type === "income");
    const costs = data.accounts.filter((account) => account.type === "expense" && /cost|freight|customs|handling/i.test(account.name));
    const operating = data.accounts.filter((account) => account.type === "expense" && !costs.includes(account));
    const revenueTotal = sum(revenue.map((item) => item.balance));
    const costTotal = sum(costs.map((item) => item.balance));
    const operatingTotal = sum(operating.map((item) => item.balance));
    return [accountSection("Revenue", revenue, revenueTotal), accountSection("Cost of Sales", costs, costTotal), summarySection("Gross Profit", revenueTotal - costTotal), accountSection("Operating Expenses", operating, operatingTotal), summarySection("Net Profit / Loss", revenueTotal - costTotal - operatingTotal)];
  }
  if (type === "balance-sheet") {
    const assets = data.accounts.filter((account) => account.type === "asset");
    const liabilities = data.accounts.filter((account) => account.type === "liability");
    const equity = data.accounts.filter((account) => account.type === "equity");
    const assetTotal = sum(assets.map((item) => item.balance));
    const liabilityTotal = sum(liabilities.map((item) => item.balance));
    const retainedEarnings = data.summary.profit;
    const equityTotal = sum(equity.map((item) => item.balance)) + retainedEarnings;
    return [accountSection("Assets", assets, assetTotal), accountSection("Liabilities", liabilities, liabilityTotal), accountSection("Equity", equity, equityTotal), { title: "Accounting Equation", table: { columns: ["Total Assets", "Total Liabilities + Equity", "Difference"], rows: [[assetTotal, liabilityTotal + equityTotal, assetTotal - liabilityTotal - equityTotal]], currencyColumns: [0, 1, 2] } }];
  }
  if (type === "cash-flow-statement") {
    const receipts = sum(data.payments.filter((item) => inRange(item.paymentDate, from, to) && item.paymentType === "customer").map((item) => item.amount));
    const paidExpenses = sum(data.expenses.filter((item) => inRange(item.paidAt, from, to) && item.status === "paid").map((item) => item.totalAmount));
    const net = receipts - paidExpenses;
    const opening = data.summary.cash - net;
    return [summaryTable("Operating Activities", [["Customer receipts", receipts], ["Payments for expenses", -paidExpenses], ["Net cash from operating activities", net]]), summaryTable("Investing Activities", [["Net investing cash flow", 0]]), summaryTable("Financing Activities", [["Net financing cash flow", 0]]), summaryTable("Cash Reconciliation", [["Net cash increase / decrease", net], ["Opening cash balance", opening], ["Closing cash balance", data.summary.cash]])];
  }
  if (type === "trial-balance") {
    const rows = data.accounts.map((account) => [account.code, account.name, account.normalBalance === "debit" ? Math.max(account.balance, 0) : Math.max(-account.balance, 0), account.normalBalance === "credit" ? Math.max(account.balance, 0) : Math.max(-account.balance, 0)]);
    return [{ title: "Trial Balance", table: { columns: ["Account Code", "Account Name", "Debit", "Credit"], rows: [...rows, ["", "Total", sum(rows.map((row) => Number(row[2]))), sum(rows.map((row) => Number(row[3])))]] as (string | number)[][], currencyColumns: [2, 3] } }];
  }
  if (type === "accounts-receivable-aging") return [agingSection("Customer", data.invoices.filter((invoice) => invoice.balanceDue > 0 && inRange(invoice.issueDate, from, to)).map((invoice) => ({ name: invoice.customerName, dueDate: invoice.dueDate, amount: invoice.balanceDue })))];
  if (type === "accounts-payable-aging") return [agingSection("Supplier", data.expenses.filter((expense) => expense.status !== "paid" && inRange(expense.paidAt || new Date().toISOString(), from, to)).map((expense) => ({ name: expense.vendor || "Supplier", dueDate: expense.paidAt, amount: expense.totalAmount })))];
  if (type === "revenue-by-shipment") return [{ title: "Shipment Revenue", table: { columns: ["Shipment Number", "Customer", "Route", "Cargo Type", "Revenue", "Payment Status", "Date"], rows: data.invoices.filter((invoice) => invoice.shipmentId && inRange(invoice.issueDate, from, to)).map((invoice) => [invoice.shipmentNumber || invoice.shipmentId || "", invoice.customerName, invoice.shipmentRoute, invoice.cargoType, invoice.totalAmount, invoice.status, invoice.issueDate]), currencyColumns: [4] } }];
  return [{ title: "Expenses", table: { columns: ["Expense Date", "Category", "Description", "Payment Method", "Amount"], rows: data.expenses.filter((expense) => inRange(expense.paidAt, from, to)).map((expense) => [expense.paidAt || "Unpaid", expense.category, expense.description, expense.status, expense.totalAmount]), currencyColumns: [4] } }];
}

function accountSection(title: string, accounts: AccountingData["accounts"], total: number): ReportSection { return { title, table: { columns: ["Account Code", "Account Name", "Amount"], rows: accounts.map((account) => [account.code, account.name, account.balance]), currencyColumns: [2] }, total }; }
function summarySection(title: string, amount: number): ReportSection { return { title, table: { columns: ["Description", "Amount"], rows: [[title, amount]], currencyColumns: [1] }, total: amount }; }
function summaryTable(title: string, rows: [string, number][]): ReportSection { return { title, table: { columns: ["Description", "Amount"], rows, currencyColumns: [1] } }; }
function agingSection(label: string, items: { name: string; dueDate: string; amount: number }[]): ReportSection {
  const grouped = new Map<string, number[]>();
  for (const item of items) { const values = grouped.get(item.name) ?? [0, 0, 0, 0, 0]; values[agingBucket(item.dueDate)] += item.amount; grouped.set(item.name, values); }
  return { title: `${label} Aging`, table: { columns: [label, "Current", "1–30 Days", "31–60 Days", "61–90 Days", "90+ Days", "Total"], rows: Array.from(grouped, ([name, values]) => [name, ...values, sum(values)]), currencyColumns: [1, 2, 3, 4, 5, 6] } };
}
function agingBucket(dueDate: string) { if (!dueDate) return 0; const days = Math.floor((Date.now() - new Date(dueDate).getTime()) / 86400000); return days <= 0 ? 0 : days <= 30 ? 1 : days <= 60 ? 2 : days <= 90 ? 3 : 4; }
function inRange(value: string, from: string, to: string) { if (!value) return !from && !to; const date = value.slice(0, 10); return (!from || date >= from) && (!to || date <= to); }
function sum(values: number[]) { return values.reduce((total, value) => total + (Number.isFinite(value) ? value : 0), 0); }
function renderSection(section: ReportSection, currency: string) {
  const rows = section.table.rows.length ? section.table.rows.map((row) => `<tr>${row.map((cell, index) => `<td class="${section.table.currencyColumns?.includes(index) ? "num" : ""}">${section.table.currencyColumns?.includes(index) ? formatMoney(Number(cell), currency) : escapeHtml(String(cell))}</td>`).join("")}</tr>`).join("") : `<tr><td colspan="${section.table.columns.length}" class="empty">No transactions for this period.</td></tr>`;
  return `<section class="section"><h3>${escapeHtml(section.title)}</h3><table><thead><tr>${section.table.columns.map((column, index) => `<th class="${section.table.currencyColumns?.includes(index) ? "num" : ""}">${escapeHtml(column)}</th>`).join("")}</tr></thead><tbody>${rows}</tbody></table>${section.total === undefined ? "" : `<div class="total"><span>Total</span><span>${formatMoney(section.total, currency)}</span></div>`}</section>`;
}
function formatMoney(value: number, currency: string) { const formatted = new Intl.NumberFormat("en", { style: "currency", currency, minimumFractionDigits: 2 }).format(Math.abs(value)); return value < 0 ? `(${formatted})` : formatted; }
function escapeHtml(value: string) { return value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character); }
